-- Run once in the Supabase SQL editor so signed-in website users can record
-- and read the change log. Existing data is preserved.
create table if not exists public.punch_item_audit (
  id bigint generated by default as identity primary key,
  actor_name text not null check (char_length(trim(actor_name)) between 2 and 120),
  session_id uuid not null,
  action text not null,
  item_id uuid null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists punch_item_audit_created_at_idx
  on public.punch_item_audit (created_at desc);
create index if not exists punch_item_audit_item_id_idx
  on public.punch_item_audit (item_id);

alter table public.punch_item_audit enable row level security;

drop policy if exists "Authenticated users can insert audit entries" on public.punch_item_audit;
create policy "Authenticated users can insert audit entries"
  on public.punch_item_audit for insert
  to authenticated
  with check (char_length(trim(actor_name)) between 2 and 120);

drop policy if exists "Authenticated users can read audit entries" on public.punch_item_audit;
create policy "Authenticated users can read audit entries"
  on public.punch_item_audit for select
  to authenticated
  using (true);
